package com.ldlda.chesscom_stats.helpers;

import java.util.HashMap;
import java.util.Map;

public class Countries {
    public static final Map<String, String> COUNTRY_CODE = new HashMap<>();

    static {
        COUNTRY_CODE.put("AD", "Andorra");
        COUNTRY_CODE.put("AE", "United Arab Emirates");
        COUNTRY_CODE.put("AF", "Afghanistan");
        COUNTRY_CODE.put("AG", "Antigua and Barbuda");
        COUNTRY_CODE.put("AI", "Anguilla");
        COUNTRY_CODE.put("AL", "Albania");
        COUNTRY_CODE.put("AM", "Armenia");
        COUNTRY_CODE.put("AO", "Angola");
        COUNTRY_CODE.put("AQ", "Antarctica");
        COUNTRY_CODE.put("AR", "Argentina");
        COUNTRY_CODE.put("AS", "American Samoa");
        COUNTRY_CODE.put("AT", "Austria");
        COUNTRY_CODE.put("AU", "Australia");
        COUNTRY_CODE.put("AW", "Aruba");
        COUNTRY_CODE.put("AX", "Åland Islands");
        COUNTRY_CODE.put("AZ", "Azerbaijan");
        COUNTRY_CODE.put("BA", "Bosnia and Herzegovina");
        COUNTRY_CODE.put("BB", "Barbados");
        COUNTRY_CODE.put("BD", "Bangladesh");
        COUNTRY_CODE.put("BE", "Belgium");
        COUNTRY_CODE.put("BF", "Burkina Faso");
        COUNTRY_CODE.put("BG", "Bulgaria");
        COUNTRY_CODE.put("BH", "Bahrain");
        COUNTRY_CODE.put("BI", "Burundi");
        COUNTRY_CODE.put("BJ", "Benin");
        COUNTRY_CODE.put("BL", "Saint Barthélemy");
        COUNTRY_CODE.put("BM", "Bermuda");
        COUNTRY_CODE.put("BN", "Brunei Darussalam");
        COUNTRY_CODE.put("BO", "Bolivia");
        COUNTRY_CODE.put("BQ", "Bonaire");
        COUNTRY_CODE.put("BR", "Brazil");
        COUNTRY_CODE.put("BS", "Bahamas");
        COUNTRY_CODE.put("BT", "Bhutan");
        COUNTRY_CODE.put("BV", "Bouvet Island");
        COUNTRY_CODE.put("BW", "Botswana");
        COUNTRY_CODE.put("BY", "Belarus");
        COUNTRY_CODE.put("BZ", "Belize");
        COUNTRY_CODE.put("CA", "Canada");
        COUNTRY_CODE.put("CC", "Cocos (Keeling) Islands");
        COUNTRY_CODE.put("CD", "Congo");
        COUNTRY_CODE.put("CF", "Central African Republic");
        COUNTRY_CODE.put("CG", "Congo");
        COUNTRY_CODE.put("CH", "Switzerland");
        COUNTRY_CODE.put("CI", "Côte d'Ivoire");
        COUNTRY_CODE.put("CK", "Cook Islands");
        COUNTRY_CODE.put("CL", "Chile");
        COUNTRY_CODE.put("CM", "Cameroon");
        COUNTRY_CODE.put("CN", "China");
        COUNTRY_CODE.put("CO", "Colombia");
        COUNTRY_CODE.put("CR", "Costa Rica");
        COUNTRY_CODE.put("CU", "Cuba");
        COUNTRY_CODE.put("CV", "Cabo Verde");
        COUNTRY_CODE.put("CW", "Curaçao");
        COUNTRY_CODE.put("CX", "Christmas Island");
        COUNTRY_CODE.put("CY", "Cyprus");
        COUNTRY_CODE.put("CZ", "Czechia");
        COUNTRY_CODE.put("DE", "Germany");
        COUNTRY_CODE.put("DJ", "Djibouti");
        COUNTRY_CODE.put("DK", "Denmark");
        COUNTRY_CODE.put("DM", "Dominica");
        COUNTRY_CODE.put("DO", "Dominican Republic");
        COUNTRY_CODE.put("DZ", "Algeria");
        COUNTRY_CODE.put("EC", "Ecuador");
        COUNTRY_CODE.put("EE", "Estonia");
        COUNTRY_CODE.put("EG", "Egypt");
        COUNTRY_CODE.put("EH", "Western Sahara");
        COUNTRY_CODE.put("ER", "Eritrea");
        COUNTRY_CODE.put("ES", "Spain");
        COUNTRY_CODE.put("ET", "Ethiopia");
        COUNTRY_CODE.put("FI", "Finland");
        COUNTRY_CODE.put("FJ", "Fiji");
        COUNTRY_CODE.put("FK", "Falkland Islands (Malvinas)");
        COUNTRY_CODE.put("FM", "Micronesia");
        COUNTRY_CODE.put("FO", "Faroe Islands");
        COUNTRY_CODE.put("FR", "France");
        COUNTRY_CODE.put("GA", "Gabon");
        COUNTRY_CODE.put("GB", "United Kingdom");
        COUNTRY_CODE.put("GD", "Grenada");
        COUNTRY_CODE.put("GE", "Georgia");
        COUNTRY_CODE.put("GF", "French Guiana");
        COUNTRY_CODE.put("GG", "Guernsey");
        COUNTRY_CODE.put("GH", "Ghana");
        COUNTRY_CODE.put("GI", "Gibraltar");
        COUNTRY_CODE.put("GL", "Greenland");
        COUNTRY_CODE.put("GM", "Gambia");
        COUNTRY_CODE.put("GN", "Guinea");
        COUNTRY_CODE.put("GP", "Guadeloupe");
        COUNTRY_CODE.put("GQ", "Equatorial Guinea");
        COUNTRY_CODE.put("GR", "Greece");
        COUNTRY_CODE.put("GT", "Guatemala");
        COUNTRY_CODE.put("GU", "Guam");
        COUNTRY_CODE.put("GW", "Guinea-Bissau");
        COUNTRY_CODE.put("GY", "Guyana");
        COUNTRY_CODE.put("HK", "Hong Kong");
        COUNTRY_CODE.put("HN", "Honduras");
        COUNTRY_CODE.put("HR", "Croatia");
        COUNTRY_CODE.put("HT", "Haiti");
        COUNTRY_CODE.put("HU", "Hungary");
        COUNTRY_CODE.put("ID", "Indonesia");
        COUNTRY_CODE.put("IE", "Ireland");
        COUNTRY_CODE.put("IL", "Israel");
        COUNTRY_CODE.put("IM", "Isle of Man");
        COUNTRY_CODE.put("IN", "India");
        COUNTRY_CODE.put("IO", "British Indian Ocean Territory");
        COUNTRY_CODE.put("IQ", "Iraq");
        COUNTRY_CODE.put("IR", "Iran");
        COUNTRY_CODE.put("IS", "Iceland");
        COUNTRY_CODE.put("IT", "Italy");
        COUNTRY_CODE.put("JE", "Jersey");
        COUNTRY_CODE.put("JM", "Jamaica");
        COUNTRY_CODE.put("JO", "Jordan");
        COUNTRY_CODE.put("JP", "Japan");
        COUNTRY_CODE.put("KE", "Kenya");
        COUNTRY_CODE.put("KG", "Kyrgyzstan");
        COUNTRY_CODE.put("KH", "Cambodia");
        COUNTRY_CODE.put("KI", "Kiribati");
        COUNTRY_CODE.put("KM", "Comoros");
        COUNTRY_CODE.put("KN", "Saint Kitts and Nevis");
        COUNTRY_CODE.put("KP", "North Korea");
        COUNTRY_CODE.put("KR", "South Korea");
        COUNTRY_CODE.put("KW", "Kuwait");
        COUNTRY_CODE.put("KY", "Cayman Islands");
        COUNTRY_CODE.put("KZ", "Kazakhstan");
        COUNTRY_CODE.put("LA", "Laos");
        COUNTRY_CODE.put("LB", "Lebanon");
        COUNTRY_CODE.put("LC", "Saint Lucia");
        COUNTRY_CODE.put("LI", "Liechtenstein");
        COUNTRY_CODE.put("LK", "Sri Lanka");
        COUNTRY_CODE.put("LR", "Liberia");
        COUNTRY_CODE.put("LS", "Lesotho");
        COUNTRY_CODE.put("LT", "Lithuania");
        COUNTRY_CODE.put("LU", "Luxembourg");
        COUNTRY_CODE.put("LV", "Latvia");
        COUNTRY_CODE.put("LY", "Libya");
        COUNTRY_CODE.put("MA", "Morocco");
        COUNTRY_CODE.put("MC", "Monaco");
        COUNTRY_CODE.put("MD", "Moldova, Republic of");
        COUNTRY_CODE.put("ME", "Montenegro");
        COUNTRY_CODE.put("MF", "Saint Martin (French part)");
        COUNTRY_CODE.put("MG", "Madagascar");
        COUNTRY_CODE.put("MH", "Marshall Islands");
        COUNTRY_CODE.put("MK", "North Macedonia");
        COUNTRY_CODE.put("ML", "Mali");
        COUNTRY_CODE.put("MM", "Myanmar");
        COUNTRY_CODE.put("MN", "Mongolia");
        COUNTRY_CODE.put("MO", "Macao");
        COUNTRY_CODE.put("MP", "Northern Mariana Islands");
        COUNTRY_CODE.put("MQ", "Martinique");
        COUNTRY_CODE.put("MR", "Mauritania");
        COUNTRY_CODE.put("MS", "Montserrat");
        COUNTRY_CODE.put("MT", "Malta");
        COUNTRY_CODE.put("MU", "Mauritius");
        COUNTRY_CODE.put("MV", "Maldives");
        COUNTRY_CODE.put("MW", "Malawi");
        COUNTRY_CODE.put("MX", "Mexico");
        COUNTRY_CODE.put("MY", "Malaysia");
        COUNTRY_CODE.put("MZ", "Mozambique");
        COUNTRY_CODE.put("NA", "Namibia");
        COUNTRY_CODE.put("NC", "New Caledonia");
        COUNTRY_CODE.put("NE", "Niger");
        COUNTRY_CODE.put("NF", "Norfolk Island");
        COUNTRY_CODE.put("NG", "Nigeria");
        COUNTRY_CODE.put("NI", "Nicaragua");
        COUNTRY_CODE.put("NL", "Netherlands");
        COUNTRY_CODE.put("NO", "Norway");
        COUNTRY_CODE.put("NP", "Nepal");
        COUNTRY_CODE.put("NR", "Nauru");
        COUNTRY_CODE.put("NU", "Niue");
        COUNTRY_CODE.put("NZ", "New Zealand");
        COUNTRY_CODE.put("OM", "Oman");
        COUNTRY_CODE.put("PA", "Panama");
        COUNTRY_CODE.put("PE", "Peru");
        COUNTRY_CODE.put("PF", "French Polynesia");
        COUNTRY_CODE.put("PG", "Papua New Guinea");
        COUNTRY_CODE.put("PH", "Philippines");
        COUNTRY_CODE.put("PK", "Pakistan");
        COUNTRY_CODE.put("PL", "Poland");
        COUNTRY_CODE.put("PM", "Saint Pierre and Miquelon");
        COUNTRY_CODE.put("PN", "Pitcairn");
        COUNTRY_CODE.put("PR", "Puerto Rico");
        COUNTRY_CODE.put("PS", "Palestine, State of");
        COUNTRY_CODE.put("PT", "Portugal");
        COUNTRY_CODE.put("PW", "Palau");
        COUNTRY_CODE.put("PY", "Paraguay");
        COUNTRY_CODE.put("QA", "Qatar");
        COUNTRY_CODE.put("RE", "Réunion");
        COUNTRY_CODE.put("RO", "Romania");
        COUNTRY_CODE.put("RS", "Serbia");
        COUNTRY_CODE.put("RU", "Russian Federation");
        COUNTRY_CODE.put("RW", "Rwanda");
        COUNTRY_CODE.put("SA", "Saudi Arabia");
        COUNTRY_CODE.put("SB", "Solomon Islands");
        COUNTRY_CODE.put("SC", "Seychelles");
        COUNTRY_CODE.put("SD", "Sudan");
        COUNTRY_CODE.put("SE", "Sweden");
        COUNTRY_CODE.put("SG", "Singapore");
        COUNTRY_CODE.put("SH", "Saint Helena");
        COUNTRY_CODE.put("SI", "Slovenia");
        COUNTRY_CODE.put("SK", "Slovakia");
        COUNTRY_CODE.put("SL", "Sierra Leone");
        COUNTRY_CODE.put("SM", "San Marino");
        COUNTRY_CODE.put("SN", "Senegal");
        COUNTRY_CODE.put("SO", "Somalia");
        COUNTRY_CODE.put("SR", "Suriname");
        COUNTRY_CODE.put("SS", "South Sudan");
        COUNTRY_CODE.put("ST", "Sao Tome and Principe");
        COUNTRY_CODE.put("SV", "El Salvador");
        COUNTRY_CODE.put("SX", "Sint Maarten (Dutch part)");
        COUNTRY_CODE.put("SY", "Syrian Arab Republic");
        COUNTRY_CODE.put("SZ", "Eswatini");
        COUNTRY_CODE.put("TC", "Turks and Caicos Islands");
        COUNTRY_CODE.put("TD", "Chad");
        COUNTRY_CODE.put("TF", "French Southern Territories");
        COUNTRY_CODE.put("TG", "Togo");
        COUNTRY_CODE.put("TH", "Thailand");
        COUNTRY_CODE.put("TJ", "Tajikistan");
        COUNTRY_CODE.put("TK", "Tokelau");
        COUNTRY_CODE.put("TL", "Timor-Leste");
        COUNTRY_CODE.put("TM", "Turkmenistan");
        COUNTRY_CODE.put("TN", "Tunisia");
        COUNTRY_CODE.put("TO", "Tonga");
        COUNTRY_CODE.put("TR", "Türkiye");
        COUNTRY_CODE.put("TT", "Trinidad and Tobago");
        COUNTRY_CODE.put("TV", "Tuvalu");
        COUNTRY_CODE.put("TW", "Taiwan, Province of China");
        COUNTRY_CODE.put("TZ", "Tanzania, United Republic of");
        COUNTRY_CODE.put("UA", "Ukraine");
        COUNTRY_CODE.put("UG", "Uganda");
        COUNTRY_CODE.put("UM", "United States Minor Outlying Islands");
        COUNTRY_CODE.put("US", "United States of America");
        COUNTRY_CODE.put("UY", "Uruguay");
        COUNTRY_CODE.put("UZ", "Uzbekistan");
        COUNTRY_CODE.put("VA", "Holy See");
        COUNTRY_CODE.put("VC", "Saint Vincent and the Grenadines");
        COUNTRY_CODE.put("VE", "Venezuela");
        COUNTRY_CODE.put("VG", "Virgin Islands (British)");
        COUNTRY_CODE.put("VI", "Virgin Islands (U.S.)");
        COUNTRY_CODE.put("VN", "Viet Nam");
        COUNTRY_CODE.put("VU", "Vanuatu");
        COUNTRY_CODE.put("WF", "Wallis and Futuna");
        COUNTRY_CODE.put("WS", "Samoa");
        COUNTRY_CODE.put("YE", "Yemen");
        COUNTRY_CODE.put("YT", "Mayotte");
        COUNTRY_CODE.put("ZA", "South Africa");
        COUNTRY_CODE.put("ZM", "Zambia");
        COUNTRY_CODE.put("ZW", "Zimbabwe");
    }
}
